# image will be published to ghcr.io/<user>/<name>
name: bluegnome
# description will be included in the image's metadata
description: gnome with personal cherry-picked stuffs

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: ../modules/fonts.yml
  - from-file: ../modules/gnome-extensions.yml

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
       - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
       - starship
       - android-tools
       - calibre
       - alacritty
       - fish 
       - zsh
       - neovim
       - ddcutil
       - newsboat

    remove:

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - org.onlyoffice.desktopeditors
        - one.ablaze.floorp
        - io.bassi.Amberol
        - com.notesnook.Notesnook
        - org.telegram.desktop
        - org.localsend.localsend_app
        - org.qbittorrent.qBittorrent
      remove:
        - org.mozilla.firefox
        - org.gnome.DejaDup
        - org.gnome.TextEditor


  - type: signing # this sets up the proper policy & signing files for signed images to work fully

